/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Thomas Koenders (https://sketchfab.com/73799)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lego-star-destroyer-1361688ca679427c81406db39739174f
Title: LEGO Star Destroyer
*/

import React, {useEffect, useRef} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import {useMotionValue, useSpring} from "framer-motion";
import {useFrame} from "@react-three/fiber";
import { resolveModel } from "../utils/assetUrl";

type ModelProps = {
    position?: [number, number, number];
    rotation?: [number, number, number];
    scale?: number;
    [key: string]: unknown;
};

export function SpaceShip(props: ModelProps) {
    const group = useRef<any>(null)
    const { nodes, materials, animations } = useGLTF(resolveModel("lego_star_destroyer.glb")) as any
    const { actions: _actions } = useAnimations(animations, group as any)


    const xPosition = useMotionValue(5);
    const xSpring = useSpring(xPosition.get(), {damping: 50});
    const yPosition = useMotionValue(1);
    const ySpring = useSpring(yPosition.get(), {damping: 50});

    useEffect(() => {
        ySpring.set(.85)
        xSpring.set(1.7);
    }, [xSpring,  ySpring]);

    useFrame(() => {
        if (!group.current) return;
        group.current.position.x = xSpring.get();
        group.current.position.y = ySpring.get();
    })

    return (
        <group ref={group} {...props} dispose={null} position={props.position || [10, -1.7, 0]} rotation={[-Math.PI / 2, 0, -1]} scale={props.scale || .25}>
            {/*{console.log(props.position, props.scale)}*/}
            <group name="Sketchfab_Scene">
                <group name="Sketchfab_model" >
                    <group name="a0398c70f5d1493987ccf7ad99cfb176fbx" >
                        <group name="Object_2">
                            <group name="RootNode">
                                <group
                                    name="Star_Destroyer">
                                    <mesh
                                        name="Star_Destroyer_Dark_Gray_0"

                                        geometry={nodes.Star_Destroyer_Dark_Gray_0.geometry}
                                        material={materials.Dark_Gray}
                                    />
                                    <mesh
                                        name="Star_Destroyer_Black_0"

                                        geometry={nodes.Star_Destroyer_Black_0.geometry}
                                        material={materials.Black}
                                    />
                                    <mesh
                                        name="Star_Destroyer_AquaTransparent_0"

                                        geometry={nodes.Star_Destroyer_AquaTransparent_0.geometry}
                                        material={materials.AquaTransparent}
                                    />
                                    <mesh
                                        name="Star_Destroyer_Light_Gray_0"

                                        geometry={nodes.Star_Destroyer_Light_Gray_0.geometry}
                                        material={materials.Light_Gray}
                                    />
                                    <mesh
                                        name="Star_Destroyer_Plastic_0"

                                        geometry={nodes.Star_Destroyer_Plastic_0.geometry}
                                        material={materials.Plastic}
                                    />
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload(resolveModel("lego_star_destroyer.glb"))
